replicaCount: 1

image:
  repository: ormuco-backend
  tag: "1.0"
  pullPolicy: IfNotPresent

env:
  - name: MYSQL_ROOT_PASSWORD
    value: "ormuco"
  - name: MYSQL_DATABASE
    value: "ormucodb"
  - name: "MYSQL_USER"
    value: "ormuco"
  - name: "MYSQL_PASSWORD"
    value: "ormuco"

service:
  type: ClusterIP
  port: 80
  