apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ormuco-database.fullname" . }}
  labels:
    {{- include "ormuco-database.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ormuco-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ormuco-database.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ include "ormuco-database.fullname" . }}
