apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ormuco-database.fullname" . }}
  labels:
    {{- include "ormuco-database.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # You can modify this as needed or parameterize it in values.yaml
