apiVersion: v1
kind: Service
metadata:
  name: {{ include "ormuco-database.fullname" . }}
  labels:
    {{- include "ormuco-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3306
  selector:
    {{- include "ormuco-database.selectorLabels" . | nindent 4 }}
