apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ormuco-backend.fullname" . }}
  labels:
    {{- include "ormuco-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ormuco-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ormuco-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ormuco-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              value: ormuco-database
            - name: MYSQL_PORT
              value: "3306" 