apiVersion: v1
kind: Service
metadata:
  name: ormuco-database-service
  labels:
    app: ormuco-database
spec:
  selector:
    app: ormuco-database
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
