apiVersion: v1
kind: Service
metadata:
  name: {{ include "ormuco-backend.fullname" . }}
  labels:
    {{- include "ormuco-backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "ormuco-backend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
