apiVersion: v1
kind: Service
metadata:
  name: ormuco-backend-service
  labels:
    app: ormuco-backend
spec:
  selector:
    app: ormuco-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
